name: Run the source code lint checker
on:
  push:
    branches:
      - '*'
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: yarn
      - name: Prettier
        run: yarn format
      - name: Lint
        run: yarn lint
